---
title: "compile_crt_files"
author: "William F. Lamb"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())
library(openxlsx)
library(rvest)
library(httr)
library(countrycode)
library(tidyverse)
library(tools)


```

## Check BTR and AI inventory websites for new files (https://unfccc.int/first-biennial-transparency-reports, https://unfccc.int/ghg-inventories-annex-i-parties/2025) 

``` {r website_fns}

# Function to fetch and parse the webpage
fetch_webpage <- function(url) {
  tryCatch({
    page <- GET(url)
    if (status_code(page) == 200) {
      content <- read_html(page)
      return(content)
    } else {
      stop("Failed to fetch the webpage. HTTP status code: ", status_code(page))
    }
  }, error = function(e) {
    message("Error: ", e$message)
    return(NULL)
  })
}

# Function to extract links with title "CRT"
extract_crt_links <- function(webpage) {
  tryCatch({
    # Select anchor (<a>) elements where title contains "CRT"
    elements <- webpage %>%
      html_elements("a[title*='CRT']")  # Matches any <a> tag with 'CRT' in the title
    
    # Extract href (link) and title
    links <- elements %>% html_attr("href")
    titles <- elements %>% html_attr("title")
    
    if (length(links) == 0) {
      message("No CRT links found on the page.")
      return(NULL)
    } else {
      # Prepend the base URL to form complete links
      base_url <- "https://unfccc.int"
      full_links <- sapply(links, function(link) {
        if (startsWith(link, "/")) {
          paste0(base_url, link)
        } else {
          link
        }
      })
      
      # Extract country names (assume the first word(s) before the first period in the title)
      country_names <- sapply(titles, function(title) {
        strsplit(title, "\\.", fixed = FALSE)[[1]][1]
      })
      
      # Combine country names and links into a data frame
      result <- data.frame(country = country_names, link = full_links, stringsAsFactors = FALSE)
      return(result)
    }
  }, error = function(e) {
    message("Error during link extraction: ", e$message)
    return(NULL)
  })
}

```

``` {r check_btr_ai_webpages}

## Check BTR webpage

btr_webpage <- fetch_webpage("https://unfccc.int/first-biennial-transparency-reports")

btr_links <- extract_crt_links(btr_webpage) %>% 
  mutate(iso=countrycode(country,'country.name','iso3c'))

load("sources/data_crt_files.RData")
files_crts <- files_crts %>% 
  select(iso) %>% 
  distinct() %>% 
  mutate(compiled=1)

btr_links <- btr_links %>% 
  left_join(.,files_crts,by=join_by(iso)) %>% 
  filter(is.na(compiled))


## Check against rejected CRTs
rejected_crts <- read.xlsx("sources/excluded/excluded_files.xlsx") %>% 
  mutate(excluded=1)

btr_links <- btr_links %>% 
  left_join(.,rejected_crts %>% select(iso,excluded),by=join_by(iso))



## Check Annex I national inventory webpage


ai_webpage <- fetch_webpage("https://unfccc.int/ghg-inventories-annex-i-parties/2026")

ai_links <- extract_crt_links(ai_webpage) %>% 
  mutate(iso=countrycode(country,'country.name','iso3c'))

load("sources/data_crt_files.RData")
files_crts <- files_crts %>% 
  select(iso,year_submission) %>% 
  distinct() %>% 
  filter(year_submission==2026) %>% 
  mutate(compiled=1)

ai_links <- ai_links %>% 
  left_join(.,files_crts,by=join_by(iso)) %>% 
  filter(is.na(compiled))



## Now go and download the files in those links, put them in the "sources/new/" folder

rm(files_crts)

```

## Extract new zip files

``` {r extract_zip_files}

zips <- data.frame(dir=list.files(path = "sources/new/", pattern = "\\.zip$", full.names = TRUE))

for (zip_file in zips$dir) {
  # Get the directory path and the base name of the zip file
  dir_path <- dirname(zip_file)
  base_name <- file_path_sans_ext(basename(zip_file))
  
  # Create a new directory for the zip file
  new_dir <- file.path(dir_path, base_name)
  dir.create(new_dir, showWarnings = FALSE)
  
  # Extract the zip file into the new directory
  unzip(zipfile = zip_file, exdir = new_dir)
  
  # List all files in the new directory
  extracted_files <- list.files(new_dir, recursive = TRUE, full.names = TRUE)
  
  # Check if all extracted files are .xlsx files
  non_xlsx_files <- extracted_files[!grepl("\\.xlsx$", extracted_files)]
  if (length(non_xlsx_files) > 0) {
    warning(paste("Non-.xlsx files found in:", new_dir))
  }
}

## Delete the extracted zip files

for (zip_file in zips$dir) {
  file.remove(zip_file)
}


## Check there are no subfolders or funny files!!


## unzip every folder in a folder... (some special cases)
# special_folder <- data.frame(dir=list.files(path = "sources/new/EU_CRT_1990_2023/zipped", pattern = "\\.zip$", full.names = TRUE))
# 
# for (zip_file in special_folder$dir) {
#   
#   unzip(zipfile = zip_file, exdir = "sources/new/EU_CRT_1990_2023")
#   
# }


```

## Scan new files and build a data frame with the file links and names 

``` {r scan_new_files}

folders <- data.frame(dir=list.files(path = "sources/new/"))
new_crt_files = data.frame(dir=NA,files=NA,country=NA,year_file=NA,year_submission=NA,status_summaries=NA,status_energy=NA)

for (i in 1:length(folders$dir)) {
  
  files <- data.frame(dir=folders$dir[i],
                      files=list.files(path = paste0("sources/new/",folders$dir[i])),
                      year_file=NA,
                      country=NA,
                      year_submission=NA,
                      status_summaries="notcompiled",
                      status_energy="notcompiled")
  
  for (j in 1:length(files$files)) {
    
    ## Extract the country name, file year and submission year from the top of Table1 in every sheet
    
    # file_info <- read.xlsx(xlsxFile = paste0("sources/new/",folders$dir[i],"/",files$files[j]),
    #                        sheet = paste0("Table1"),rows = 1:3,colNames = FALSE)
    # 
    
    file_path <- paste0("sources/new/",folders$dir[i],"/",files$files[j])
    
    file_info <- tryCatch(
      read.xlsx(
        xlsxFile = file_path,
        sheet = "Table1",
        rows = 1:3,
        colNames = FALSE
      ),
      error = function(e) {
        read.xlsx(
          xlsxFile = file_path,
          sheet = "Summary1",
          rows = 1:3,
          colNames = FALSE
        )
      }
    )
    
    
    files$year_file[j] <- str_extract(file_info$X2[1], "\\d{4}")
    files$year_submission[j] <- str_extract(file_info$X2[2], "\\d{4}")
    files$country[j] <- file_info$X2[3]
    
    ## The following lines capture cases where file information was put into an ajoined column (e.g. ISR)
    
    if (is.na(files$year_file[j]) &  length(names(file_info))>2 ) {
      
      files$year_file[j] <- str_extract(file_info$X3[1], "\\d{4}")
      files$year_submission[j] <- str_extract(file_info$X3[2], "\\d{4}")
      files$country[j] <- file_info$X3[3]
      
    }
    
    
  }
  
  new_crt_files <- rbind(new_crt_files,files)
  
}

new_crt_files <- new_crt_files %>% 
  filter(!is.na(dir)) %>% 
  mutate(iso=countrycode(country,"country.name","iso3c")) %>%
  mutate(iso=ifelse(country=="EUU","EU27",iso)) %>% 
  mutate(country=countrycode(iso,"iso3c","country.name")) %>% 
  mutate(country=ifelse(iso=="EU27","European Union",country))


## check for issues

check <- new_crt_files %>% 
  filter(is.na(country) | is.na(year_file) | is.na(year_submission))





```

``` {r save}

load("sources/data_crt_files.RData")

files_crts <- files_crts %>%
  bind_rows(.,new_crt_files)

save(files_crts,file="sources/data_crt_files.RData")


```
