---
title: "compile_crt_summaries"
author: "William F. Lamb"
output: word_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())
library(openxlsx)
library(rvest)
library(httr)
library(countrycode)
library(tidyverse)
library(tools)

load("sources/data_crt_files.RData")
new_crt_files <- files_crts %>% filter(status_summaries=="notcompiled")

new_crt_files <- files_crts %>% filter(iso=="EU27")

```



## Scan the summaries and extract data

```{r scan_summaries}

# Table10s1, Table10s2, Table10s3, Table10s4, Table10s5, Table10s6
# Assume GWP is always AR5


## for the summary sheets we only need the file for the latest year

files_to_extract <- new_crt_files %>%
  arrange(iso,year_file) %>% 
  group_by(iso,dir) %>% 
  mutate(include=ifelse(year_file==last(year_file),1,0)) %>% 
  filter(include==1)


## prepare data frames

data_crts <- data.frame()
data_crts_memos <- data.frame()


#i=54

for (i in 1:length(files_to_extract$country)) {
  
  table_1 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s1"),
                       startRow = 8) %>% 
    select("GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktCO2e") %>% 
    mutate(gas = "ghg") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  table_2 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s2"),
                       startRow = 8) %>%
    select("GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktCO2") %>% 
    mutate(gas = "co2") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  table_3 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s3"),
                       startRow = 8) %>%
    select("GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktCH4e") %>% 
    mutate(gas = "ch4") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  table_4 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s4"),
                       startRow = 8) %>%
    select("GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktN2O") %>% 
    mutate(gas = "n2o") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  table_5 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s5"),
                       startRow = 8) %>%
    select("GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktCO2e") %>% 
    mutate(gas = "fgases") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  table_6 <- read.xlsx(xlsxFile = paste0("sources/new/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table10s6"),
                       startRow = 8) %>%
    select("GREENHOUSE.GAS.EMISSIONS.AND.REMOVALS",matches("^\\d{4}")) %>% 
    rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>% 
    mutate(units = "ktCO2e") %>% 
    mutate(gas = "totals") %>% 
    mutate(across(matches("^\\d{4}$"), as.character))
  
  
  ## fix up f-gas table
  table_5 <- table_5 %>% 
    mutate(gas=GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES) %>% 
    mutate(GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES="2.F. Product uses as substitutes for ODS")
  
  table_5 <- table_5 %>% 
    filter(gas %in% c("Emissions of HFCs -  CO2 equivalents (kt) (3)",
                      "Emissions of PFCs -  CO2 equivalents (kt) ",
                      "Emissions of  SF6 -  CO2 equivalents (kt) (3)",
                      "Emissions of NF3 - CO2 equivalents (kt) (3)",
                      "Unspecified mix of  HFCs and PFCs - CO2 equivalents (kt) (3)")) %>% 
    mutate(gas=ifelse(grepl("Unspecified",gas),"hfcs/pfcs (unspecified)",gas)) %>% 
    mutate(gas=ifelse(grepl("HFCs",gas),"hfcs",gas)) %>% 
    mutate(gas=ifelse(grepl("PFCs",gas),"pfcs",gas)) %>% 
    mutate(gas=ifelse(grepl("SF6",gas),"sf6",gas)) %>% 
    mutate(gas=ifelse(grepl("NF3",gas),"nf3",gas))
  
  
  ## merge co2, ch4, n2o, fgases
  table <- bind_rows(table_2,table_3,table_4,table_5)
  table <- table %>% 
    select(sector=GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES,gas,units,everything()) %>% 
    filter(!is.na(sector)) %>% 
    filter(!grepl("Note:",sector))
  table <- gather(table,year,value,-sector,-gas,-units)
  
  
  ## remove some funny character strings that crop up (Maldives)
  table$sector <- gsub('xml:space="preserve">',"",table$sector)
  
  
  ## deal with NA, NO, IE, NE
  table <- table %>% 
    mutate(value=ifelse(grepl("NA",value),NA,value)) %>% #
    mutate(value=ifelse(grepl("IE",value),NA,value)) %>% # Indicated elsewhere
    mutate(value=ifelse(grepl("NE",value),NA,value)) %>% # Not estimated
    mutate(value=ifelse(grepl("NO",value),0,value)) # Not occurring
  
  
  ## extract sector codes
  table <- table %>% 
    mutate(sector_code=sub("^(\\S+)\\s.*", "\\1", sector)) %>% 
    mutate(sector=sub("^\\S+\\s(.*)", "\\1", sector))
  
  
  ## remove spaces at the beginning of categories
  table$sector <- gsub("^\\s+", "", table$sector)
  
  
  ## extract the emissions hierarchy (just the level associated with each sector)
  table <- table %>%
    mutate(sector_level = map_int(sector_code, ~ sum(str_split(.x, "\\.")[[1]] != "")))
  
  
  ## remove memo items etc.
  memos <- table %>% 
    filter(grepl("1.D.",sector_code) | grepl("5.F.1.",sector_code))
  table <- table %>% 
    filter(!sector_code %in% c("Memo","Indirect","Total")) %>% 
    filter(!grepl("1.D.",sector_code)) %>% 
    filter(!grepl("5.F.1.",sector_code))
  
  
  ## clean up
  table <- table %>% 
    mutate(country=files_to_extract$country[i]) %>% 
    mutate(iso=files_to_extract$iso[i]) %>% 
    mutate(dir=files_to_extract$dir[i]) %>% 
    mutate(year_submission=files_to_extract$year_submission[i]) %>% 
    select(iso,country,dir,year_submission,sector_code,sector_description=sector,sector_level,gas,units,year,value) %>%
    mutate(value=as.numeric(value)) %>% 
    mutate(year=as.numeric(year))
  
  memos <- memos %>% 
    mutate(country=files_to_extract$country[i]) %>% 
    mutate(iso=files_to_extract$iso[i]) %>% 
    mutate(dir=files_to_extract$dir[i]) %>% 
    mutate(year_submission=files_to_extract$year_submission[i]) %>% 
    select(iso,country,dir,year_submission,sector_code,sector_description=sector,sector_level,gas,units,year,value) %>%
    mutate(value=as.numeric(value)) %>% 
    mutate(year=as.numeric(year))
  
  
  ## bind to dataset
  data_crts <- bind_rows(data_crts,table)
  data_crts_memos <- bind_rows(data_crts_memos,memos)
  
}

```

``` {r clean_summary_reports}

## put emissions into a clean format with no double counting and organised sectors 

data <- data_crts %>% 
  arrange(iso,country,dir,year_submission,sector_code,sector_description,sector_level,gas,units,year)


## remove trailing spaces in sector descriptions, text within round brackets
data$sector_description <- gsub("\\s+$", "", data$sector_description) 
data$sector_code <- gsub("\\s+$", "", data$sector_code) 
data$sector_description <- gsub("\\(.*?\\)", "", data$sector_description)
data$sector_description[data$sector_description=="Land use, land-use change and forestry "] <-
  "Land use, land-use change and forestry"


## fix Ecuador biomass burning issue (they renamed the 4.H. Other sector
data <- data %>% 
  mutate(sector_description=ifelse(sector_description=="Biomass burning" & sector_code=="4.H.","Other",sector_description))


## identify leaf nodes

sectors <- data %>% select(sector_code,sector_level,sector_description) %>% distinct()
sectors <- sectors %>%
  mutate(is_leaf = !sapply(sector_code, function(code) {
    any(str_detect(setdiff(sector_code, code), paste0("^", str_replace_all(code, "\\.", "\\\\."))))
  }))


## propagate sector_lv1
sectors <- sectors %>% 
  mutate(match = substr(sector_code,1,1)) %>% 
  left_join(.,sectors %>% 
              filter(sector_level==1) %>%
              mutate(match=substr(sector_code,1,1)) %>% 
              select(match,sector_lv1=sector_description),
            by = join_by(match)) %>% 
  select(-match)


## propagate sector_lv2
sectors <- sectors %>% 
  mutate(match = substr(sector_code,1,3)) %>% 
  left_join(.,sectors %>% 
              filter(sector_level==2) %>%
              mutate(match=substr(sector_code,1,3)) %>% 
              select(match,sector_lv2=sector_description),
            by = join_by(match)) %>% 
  select(-match)


## clean up sectors
sectors <- sectors %>% 
  filter(is_leaf==TRUE) %>% 
  mutate(sector_lv2=ifelse(sector_lv2=="Other",paste0(sector_lv2," (",sector_lv1,")"),sector_lv2)) %>% 
  mutate(sector_lv2=ifelse(is.na(sector_lv2),sector_lv1,sector_lv2)) %>% 
  mutate(sector_lv3=sector_description) %>% 
  mutate(sector_lv3=ifelse(sector_lv3=="Other",paste0(sector_lv3," (",sector_lv1,")"),sector_lv3)) %>% 
  select(-sector_description)


sectors <- sectors %>% 
  mutate(sector_lv3=ifelse(sector_code=="1.A.4." & sector_lv3=="Other sector","Other sectors",sector_lv3)) %>% 
  distinct()

## rejoin
data <- left_join(data,sectors,by=join_by(sector_code,sector_level))

```

``` {r check_totals}

#### check that different levels in the hierarchy add up


## calculate totals in non-leaf nodes
data_totals <- data %>% 
  filter(is.na(is_leaf)) %>% 
  group_by(iso,country,sector_code,sector_description,sector_level,gas,units,year) %>% 
  summarise(value_totals=sum(value,na.rm=TRUE))


## are totals correct at lv2?
data_test <- data %>%
  filter(is_leaf==TRUE) %>% 
  group_by(iso,country,sector_lv2,gas,units,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)) 
  
data_test <- left_join(data_test %>% rename(sector_description=sector_lv2),data_totals) %>% 
  filter(!is.na(value_totals))

data_test <- data_test %>% 
  mutate(difference_abs = value_totals-value) %>% 
  mutate(difference_rel = (difference_abs/value_totals)*100) %>% 
  filter(abs(difference_rel)>0.1)


## are totals correct at lv1?
data_test <- data %>%
  filter(is_leaf==TRUE) %>%
  group_by(iso,country,dir,year_submission,sector_lv1,gas,units,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)) 
  
data_test <- left_join(data_test %>% rename(sector_description=sector_lv1),data_totals) %>% 
  filter(!is.na(value_totals))

data_test <- data_test %>% 
  mutate(difference_abs = value_totals-value) %>% 
  mutate(difference_rel = (difference_abs/value_totals)*100) %>% 
  filter(abs(difference_rel)>0.01)


## some countries report direct and indirect emissions from N inputs to unspecified managed soils in Table 4(I)
## but they only add these to the LULUCF totals (sector 4) and not the underlying sectors (4A-4H)
## therefore we create a residual category to capture these and join it

data_residual <- data_test %>% 
  filter(gas=="n2o") %>% 
  mutate(sector_code="4.X.") %>% 
  mutate(is_leaf="TRUE") %>% 
  mutate(sector_lv1="Land use, land-use change and forestry") %>% 
  mutate(sector_lv2="Other (N from unspecified managed soils)") %>% 
  mutate(sector_lv3="Other (N from unspecified managed soils)") %>% 
  mutate(sector_description="Other (N from unspecified managed soils)") %>% 
  mutate(sector_level=2) %>% 
  select(iso,country,dir,year_submission,sector_code,sector_description,sector_level,gas,units,year,value=difference_abs,is_leaf,sector_lv1,sector_lv2,sector_lv3)

data <- rbind(data,data_residual)

sectors <- rbind(sectors,data_residual %>% ungroup() %>% 
  select(sector_code,sector_level,is_leaf,sector_lv1,sector_lv2,sector_lv3) %>% distinct()) %>%
  arrange(sector_code)

sectors_full <- data %>% select(sector_code,sector_description,sector_level) %>% distinct() %>% arrange(sector_code)


## tidy up sector hierarchy
data <- data %>% filter(!is.na(sector_lv1))


```


``` {r remove_na_years}

## remove years with only NA data (e.g. China 1990)

data <- data %>% 
  group_by(iso,year) %>% 
  mutate(year_total=sum(value,na.rm=T)) %>% 
  ungroup()

warning <- data %>% 
  filter(year_total==0) %>% 
  select(country,year) %>% 
  distinct()

if (length(warning$country) > 0) {
  for (i in 1:length(warning$country)) {
    print(paste0("Warning: ",warning$country[i]," in year ",warning$year[i]," removed due to null values"))
  }
}


data <- data %>% 
  filter(year_total!=0) %>% 
  select(-year_total)


```


``` {r apply_gwps}

## join AR5 GWPs
gwps <- read.csv("https://raw.githubusercontent.com/openclimatedata/globalwarmingpotentials/main/globalwarmingpotentials.csv",skip = 10) %>% select(gas=Species,gwp100_ar5=AR5GWP100) %>% mutate(gas=tolower(gas))

data <- data %>% left_join(.,gwps,by="gas")
data_memos <- data_crts_memos %>% left_join(.,gwps,by="gas")

data <- data %>% 
  mutate(gwp100_ar5=ifelse(!gas %in% c("ch4","n2o"),1,gwp100_ar5)) %>% 
  mutate(value_gwp100=value*gwp100_ar5)

data_memos <- data_memos %>% 
  mutate(gwp100_ar5=ifelse(!gas %in% c("ch4","n2o"),1,gwp100_ar5)) %>% 
  mutate(value_gwp100=value*gwp100_ar5)


## check units are in kt and convert to t

data <- data %>% 
  {if (any(!str_starts(.$units, "kt"))) stop("Error: Not all values in the 'units' column start with 'kt'")
    else .
  } %>%
  mutate(value_gwp100 = value_gwp100 * 1000)

data_memos <- data_memos %>% 
  {if (any(!str_starts(.$units, "kt"))) stop("Error: Not all values in the 'units' column start with 'kt'")
    else .
  } %>%
  mutate(value_gwp100 = value_gwp100 * 1000)


data <- data %>% 
  mutate(units="tCO2e (GWP100 AR5)") %>% 
  select(-gwp100_ar5,-value) %>% 
  rename(value=value_gwp100)

data_memos <- data_memos %>% 
  mutate(units="tCO2e (GWP100 AR5)") %>% 
  select(-gwp100_ar5,-value) %>% 
  rename(value=value_gwp100)


## set levels and arrange
data <- data %>% 
  mutate(gas=as.factor(gas)) %>% 
  mutate(gas=fct_relevel(gas,"co2","ch4","n2o","hfcs","pfcs","nf3","sf6","hfcs/pfcs (unspecified)"))

data_memos <- data_memos %>% 
  mutate(gas=as.factor(gas)) %>% 
  mutate(gas=fct_relevel(gas,"co2","ch4","n2o"))


## tidy up file
data <- data %>% 
  filter(!is.na(sector_lv1)) %>% 
  select(country,iso,dir,year_submission,sector_code,sector_level,sector_lv1,sector_lv2,sector_lv3,gas,units,year,value)

data_memos <- data_memos %>% 
  select(country,iso,dir,year_submission,sector_code,sector_level,sector=sector_description,gas,units,year,value)


data <- data %>% arrange(across(-ncol(data)))
data_memos <- data_memos %>% arrange(across(-ncol(data_memos)))



```


```{r compare_totals}


#################### TO DO !!!!!!!

# 
# 
# load("sources/data_crt_files.RData")
# 
# files <- data_crts %>%
#   select(iso,country,dir) %>%
#   distinct() %>%
#   mutate(keep=1)
# 
# files_crts <- files_crts %>%
#   left_join(.,files,by = join_by(dir, country, iso)) %>%
#   filter(keep==1)
# 
# 
# 
# files_crts <- files_crts %>%
#   arrange(iso,year_file) %>%
#   group_by(iso,dir) %>%
#   mutate(include=ifelse(year_file==last(year_file),1,0)) %>%
#   filter(include==1)
# 
# 
# 
# ## get the total GHG emissions from each CRT
# 
# data_crts_totals <- data.frame()
# 
# for (i in 1:length(files_crts$country)) {
# 
#   totals <- read.xlsx(xlsxFile = paste0("sources/done/",files_crts$dir[i],"/",files_crts$files[i]),
#                        sheet = paste0("Table10s1"),
#                        startRow = 8) %>%
#     select(var="GREENHOUSE.GAS.SOURCE.AND.SINK.CATEGORIES",matches("^\\d{4}")) %>%
#     rename_with(~ substr(., 1, 4), matches("^\\d{4}")) %>%
#     mutate(units = "ktCO2e") %>%
#     mutate(gas = "ghg")
# 
# 
#   totals <- totals %>%
#     filter(grepl("Total",var)) %>%
#     filter(grepl("net emissions",var)) %>%
#     gather(.,year,total,-var,-units,-gas) %>%
#     mutate(iso=files_crts$iso[i]) %>%
#     mutate(year=as.numeric(year)) %>%
#     mutate(total=as.numeric(total)*1000) %>%
#     select(iso,year,total)
# 
#   data_crts_totals <- bind_rows(data_crts_totals,totals)
# 
# 
# }
# 
# 
# # do my leaf node emissions sum up to totals in the CRT summaries?
# 
# check <- data_crts %>%
#   group_by(iso,country,year) %>%
#   summarise(value=sum(value,na.rm=TRUE))
# 
# check <- left_join(check,data_crts_totals,by=join_by(iso,year))
# 
# check <- check %>%
#   mutate(difference_abs=value-total) %>%
#   mutate(difference_rel=(difference_abs/value)*100) %>%
#   filter(abs(difference_rel)>0.01)
# 
# 
# 
# blarg <- data_crts %>%
#   filter(iso=="EU27" & year==2023) %>%
#   group_by(year,sector_lv1) %>%
#   summarise(value=sum(value,na.rm=T)/1000)
# 


```








``` {r save}

data_crts <- data
data_crts_memos <- data_memos

## Save individual files for each CRT

for (i in 1:length(files_to_extract$dir)) {
  
  file_name <- paste0(files_to_extract$country[i],"_",files_to_extract$year_submission[i])
  
  data <- data_crts %>% filter(dir==files_to_extract$dir[i]) 
  data_memos <- data_crts_memos %>% filter(dir==files_to_extract$dir[i])
  
  save(data,data_memos,file=paste0("sources/compiled/",file_name,".RData"))
  
}


## Move the compiled files to done, update file directory

for (i in 1:length(files_to_extract$dir)) {
  
  source_path <- file.path("sources/new",files_to_extract$dir[i])
  destination_path <- file.path("sources/done", files_to_extract$dir[i])
  file.rename(from = source_path, to = destination_path)
  
}


## update file structure
load("sources/data_crt_files.RData")

files_crts <- files_crts %>% 
  left_join(.,new_crt_files %>% select(dir,files,country,year_file,year_submission) %>% mutate(flag="nowdone"),
            by = join_by(dir, files, country, year_file, year_submission))

files_crts <- files_crts %>%
  mutate(flag=ifelse(is.na(flag),"ignore",flag)) %>% 
  mutate(status_summaries=ifelse(flag=="nowdone","compiled",status_summaries)) %>% 
  select(-flag)


save(files_crts,file="sources/data_crt_files.RData")




```
