---
title: "extract-forest-land"
author: "William F. Lamb"
date: "2025-05-28"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())
library(tidyverse)
library(openxlsx)

load("sources/data_crt_files.RData")

files_crts <- files_crts %>% 
  mutate(forest_land_extracted=NA)


```

```{r extract}

files_to_extract <- files_crts %>%
  arrange(iso,year_file) %>% 
  filter(is.na(forest_land_extracted))
  


## prepare data frames

data_land_area <- data.frame()

i=2

for (i in 1:length(files_to_extract$file)) {
  
  table <- read.xlsx(xlsxFile = paste0("sources/done/",files_to_extract$dir[i],"/",files_to_extract$files[i]),
                       sheet = paste0("Table4.1"),
                       startRow = 8)
  
  table <- table %>% 
    rename(area_from=`TO:`) %>% 
    filter(!str_detect(area_from, "^\\(")) %>% 
    filter(!str_detect(area_from, "FROM:")) %>% 
    filter(!str_detect(area_from, "Note:")) %>% 
    mutate(area_from = str_remove_all(area_from, "\\(\\d+\\)")) %>% 
    gather(area_to,value,-area_from)
  
  
  table$area_to=gsub("\\."," ",table$area_to)
  
  table <- table %>% 
    mutate(year=files_to_extract$year_file[i]) %>% 
    mutate(year_submission=files_to_extract$year_submission[i]) %>% 
    mutate(iso=files_to_extract$iso[i])
  
  table <- table %>% 
    select(iso,year_submission,year,area_from,area_to,value)
  
  ## bind to dataset
  data_land_area <- bind_rows(data_land_area,table)
  
}
  
save(data_land_area,file="data/data_land_area_v1.2.RData")
  
  
  
```

