---
title: "read_crt_activity_data"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
library(openxlsx)
library(tidyverse)
library(countrycode)
library(zoo)


## download files from https://unfccc.int/ghg-inventories-annex-i-parties/2024
# run scan_files.R

load("data/data_crt_files.RData")
load("data/cc_sectors.RData")

```


``` {r get_natural_disturbances_memo}


data_disturbances <- data.frame()


for (i in 1:length(files_crts$country)) {
  
  table <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table4"),
                       startRow = 8) %>% 
    select(sector=1,co2=2,ch4=3,n2o=4)

  
  table <- table %>% 
    filter(grepl("Emissions and subsequent removals from natural disturbances",sector)) %>% 
    gather(.,gas,value,-sector)
  
  
  ## deal with NA, NO, IE, NE
  table <- table %>% 
    mutate(value=ifelse(grepl("NA",value),NA,value)) %>% #
    mutate(value=ifelse(grepl("IE",value),NA,value)) %>% # Indicated elsewhere
    mutate(value=ifelse(grepl("NE",value),NA,value)) %>% # Not estimated
    mutate(value=ifelse(grepl("NO",value),0,value)) # Not occurring
  
  
  ## tidy up
  table <- table %>% 
    mutate(country=files_crts$country[i]) %>% 
    mutate(iso=files_crts$iso[i]) %>%
    mutate(year=files_crts$file_year[i]) %>% 
    mutate(units="kt") %>% 
    select(country,iso,sector,gas,units,year,value) %>% 
    mutate(value=as.numeric(value)) %>% 
    mutate(year=as.numeric(year))

  data_disturbances <- rbind(data_disturbances,table)
  
}

save(data_disturbances,file="data/data_disturbances.RData")

```




```{r get_activity_data_energy_fuelcombustion}

i=30
data_crts_activity <- data.frame()


for (i in 1208:length(files_crts$country)) {
  
  ######### Fuel combustion tables
  
  ## read tables
  table_1 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s1"),
                       startRow = 7) %>% 
    select(sector=1,activity=2,e_co2=7,e_ch4=8,e_n2o=9,cr_co2_fossil=10)
  
  table_2 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s2"),
                       startRow = 7) %>% 
    select(sector=1,activity=2,e_co2=7,e_ch4=8,e_n2o=9,cr_co2_fossil=10)
  
  table_3 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s3"),
                       startRow = 7) %>% 
    select(sector=1,activity=2,e_co2=7,e_ch4=8,e_n2o=9)
  
  table_4 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s4"),
                       startRow = 7) %>% 
    select(sector=1,activity=2,e_co2=7,e_ch4=8,e_n2o=9,cr_co2_fossil=10)
  
  table_fuel_combustion <- bind_rows(table_1,table_2,table_3,table_4) %>% 
    mutate(across(everything(), as.character))
  
  ## add activity units
  table_fuel_combustion <- table_fuel_combustion %>% 
    mutate(activity_unit="Energy consumption (TJ)") %>% 
    select(sector,activity_unit,everything())
  
  
  ## remove footnotes
  table_fuel_combustion <- table_fuel_combustion %>% mutate(remove=ifelse(grepl("Information item",sector),"yes",NA))
  table_fuel_combustion$remove <- na.locf(table_fuel_combustion$remove,na.rm=FALSE)
  table_fuel_combustion <- table_fuel_combustion %>%
    filter(is.na(remove)) %>%
    select(-remove)
  
  
  ## extract sector codes, separate fuels
  table_fuel_combustion <- table_fuel_combustion %>% 
    filter(!is.na(sector)) %>% 
    mutate(fuel = ifelse(str_detect(sector, "^[^0-9]"), sector, NA)) %>% 
    mutate(sector = ifelse(str_detect(sector, "^[^0-9]"), NA, sector)) %>% 
    mutate(sector_code=sub("^(\\S+)\\s.*", "\\1", sector))
  
  
  ## remove sector codes that don't start with a number and propagate
  table_fuel_combustion <- table_fuel_combustion %>% 
    mutate(sector_code = ifelse(grepl("^[0-9]",sector_code),sector_code,NA)) %>% 
    mutate(sector_code = na.locf(sector_code))
  
  
  ## add trailing dots to sector codes that don't have them
  table_fuel_combustion <- table_fuel_combustion %>% 
    mutate(sector_code = if_else(str_ends(sector_code, "\\.$"), sector_code, paste0(sector_code, ".")))
  
  
  ## join sector convention and trim rows
  table_fuel_combustion <- left_join(table_fuel_combustion %>% rename(sector_check=sector),cc_sectors,by="sector_code")
  table_fuel_combustion <- table_fuel_combustion %>% 
    select(sector,sector_check,sector_code,sector_level,sector_description,fuel,everything()) %>% 
    filter(!is.na(sector))
  
  
  ## create fuel totals
  table_fuel_combustion <- table_fuel_combustion %>% 
    mutate(fuel=ifelse(is.na(fuel),"Total",fuel))
  
  
  ## trim out parent nodes
  table_fuel_combustion <- table_fuel_combustion %>% 
    filter(is_leaf==TRUE)
  
  
  ######### Fugitive emissions tables (Table1.B.1, Table1.B.2, Table1.C)
  
  ## read tables
  table_5 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.B.1"),
                       startRow = 8) %>% 
    select(sector=1,activity=2,e_ch4=5,e_co2=6,cr_ch4=7,cr_co2_fossil=8) %>% 
    mutate(across(everything(), as.character))
  
  table_6 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.B.2"),
                       startRow = 8) %>% 
    select(sector=1,e_co2=8,e_ch4=9,e_n2o=10,cr_co2_fossil=11) %>% 
    mutate(across(everything(), as.character))
    
  table_7 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.C"),
                       startRow = 8) %>% 
    select(sector=1,activity=2,e_co2=4) %>% 
    mutate(across(everything(), as.character))
  
  
  table_fugitive <- bind_rows(table_5,table_6,table_7)
  
  ## clean sector codes
  table_fugitive <- table_fugitive %>% 
    mutate(sector_code = sub("^(.*?)(?=[A-Za-z]{4,}).*", "\\1", sector, perl = TRUE)) %>% 
    mutate(sector_code = str_replace_all(sector_code, "\\.\\s+", ".")) %>% 
    mutate(sector_code=if_else(str_starts(sector_code, "1.B.") | str_starts(sector_code, "1.C."),sector_code,NA)) %>% 
    mutate(sector_code = str_replace(sector_code, "Oil", "")) %>% 
    mutate(sector_code = str_replace(sector_code, "Gas", "")) %>% 
    mutate(sector_code = str_remove_all(sector_code, "\\s*\\(.*?\\)")) %>% 
    mutate(sector_code = str_trim(sector_code, side = "right")) %>% 
    select(sector,sector_code,everything())
  
  
  ## join sector convention, add activity units to coal, and trim rows
  table_fugitive <- left_join(table_fugitive %>% rename(sector_check=sector),cc_sectors,by="sector_code") 
  table_fugitive <- table_fugitive %>%  
    mutate(activity_unit=ifelse(str_starts(sector_code,"1.B.1"),"Fuel produced (Mt)",NA)) %>% 
    select(sector,sector_check,sector_code,sector_level,sector_description,activity_unit,activity,everything()) %>% 
    filter(!is.na(sector))
  
  
  ######### IPPU tables (Table2(I).A-H)
  
  table_8 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table2(I).A-H"),
                       startRow = 8) %>% 
    select(sector=1,activity_unit=2,activity=3,e_co2=7,e_ch4=8,e_n2o=9,cr_co2_fossil=10,cr_co2_bio=11,cr_ch4=12,cr_n2o=13)
  
  table_8 <- table_8 %>% 
    mutate(across(everything(), as.character))
  
  ## clean sector codes
  table_ippu <- table_8 %>% 
    mutate(sector_code=NA) %>% 
    select(sector,sector_code,everything()) %>% 
    mutate(sector_code=sub("^(\\S+)\\s.*", "\\1", sector)) %>% 
    mutate(sector_code=if_else(str_starts(sector_code,"^[^0-9]"),NA,sector_code)) %>% 
    mutate(sector_code = str_replace(sector_code, "Other", "")) %>% 
    mutate(sector_code = str_trim(sector_code, side = "right")) 
  
  
  ## join sector convention, add activity units, and trim rows
  table_ippu <- left_join(table_ippu %>% rename(sector_check=sector),cc_sectors,by="sector_code") 
  table_ippu <- table_ippu %>%  
    mutate(activity_unit=ifelse(!is.na(activity_unit),paste0(activity_unit," (kt)"),NA)) %>%  
    select(sector,sector_check,sector_code,sector_level,sector_description,activity_unit,activity,everything()) %>% 
    filter(!is.na(sector))
  
  
  ## trim out parent nodes
  table_ippu <- table_ippu %>%
    filter(is_leaf==TRUE)
  
  
  ######### IPPU F-gases (Table2(II))
  
  
  
  
  ######### Agriculture tables ()
  
  
  table_10 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.A"),
                       startRow = 9) %>% 
    select(sector=1,activity=2,e_ch4=6) %>% 
    mutate(across(everything(), as.character))
  
  table_11 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.B(a)"),
                       startRow = 9) %>% 
    select(sector=2,activity=3,e_ch4=11) %>% 
    mutate(across(everything(), as.character))
  
  table_12 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.B(b)"),
                       startRow = 7) %>% 
    select(sector=1,activity=2,e_n2o=23,e_n2o_indirecta=24,e_n2o_indirectb=25) %>%
    filter(!is.na(sector)) %>%
    mutate(across(c(e_n2o,e_n2o_indirecta,e_n2o_indirectb),as.numeric)) %>%
    mutate(e_n2o = ifelse(grepl("Indirect",sector),rowSums(across(c(e_n2o_indirecta, e_n2o_indirecta)), na.rm = TRUE),e_n2o)) %>% 
    select(sector,activity,e_n2o) %>% 
    mutate(across(everything(), as.character))
  
  table_13 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.C"),
                       startRow = 9) %>% 
    select(sector=1,activity=2,e_ch4=6) %>% 
    mutate(across(everything(), as.character)) %>% 
    mutate(sector=ifelse(str_starts(sector,"Total"),"3.C.",sector))
  
  table_14 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.D"),
                       startRow = 9) %>% 
    select(sector=1,activity_unit=2,activity=3,e_n2o=5) %>% 
    mutate(across(everything(), as.character)) %>% 
    add_row(sector="3.D.")
  
  table_15 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.E"),
                       startRow = 8) %>% 
    select(sector=1,activity=2,e_ch4=9,e_n2o=10) %>% 
    mutate(across(everything(), as.character)) %>% 
    add_row(sector="3.E.")
  
  table_16 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.F"),
                       startRow = 8) %>% 
    select(sector=1,activity=5,e_ch4=8,e_n2o=9) %>% 
    mutate(across(everything(), as.character)) %>% 
    add_row(sector="3.F.")
  
  table_17 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table3.G-J"),
                       startRow = 8) %>% 
    select(sector=1,activity=2,e_co2=4) %>% 
    mutate(across(everything(), as.character))
  
  
  table_agriculture = bind_rows(table_10,table_11,table_12,table_13,table_14,table_15,table_16,table_17)
  
  
  ## clean sector codes
  table_agriculture <- table_agriculture %>% 
    mutate(sector_code=NA) %>% 
    select(sector,sector_code,everything()) %>% 
    mutate(sector_code=sub("^(\\S+)\\s.*", "\\1", sector)) %>% 
    mutate(sector_code=if_else(str_starts(sector_code,"^[^0-9]"),NA,sector_code)) %>% 
    mutate(sector_code = str_trim(sector_code, side = "right")) 
  
  table_agriculture <- table_agriculture %>%
    mutate(filter=ifelse(is.na(e_co2),1,0)) %>% 
    mutate(filter=ifelse(is.na(e_ch4),filter+1,filter)) %>% 
    mutate(filter=ifelse(is.na(e_n2o),filter+1,filter)) %>% 
    mutate(filter=ifelse(is.na(activity),filter+1,filter)) %>% 
    mutate(filter=ifelse(sector_code %in% c("3.C.","3.D.","3.E.","3.F."),1,filter)) %>% 
    filter(filter!=4) %>% select(-filter)
    
  
  ## join sector convention, add activity units
  table_agriculture <- left_join(table_agriculture %>% rename(sector_check=sector),cc_sectors,by="sector_code") 
  table_agriculture <- table_agriculture %>%  
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.A") | str_starts(sector_code,"3.B"),"Population (1000s)",activity_unit)) %>% 
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.C"),"Harvested area (Bm2/yr)",activity_unit)) %>% 
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.E"),"Area burned (kha/yr)",activity_unit)) %>% 
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.F"),"Total biomass burned (kt dm)",activity_unit)) %>% 
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.G") | str_starts(sector_code,"3.H"),"Amount applied (t/yr)",activity_unit)) %>% 
    mutate(activity_unit=ifelse(str_starts(sector_code,"3.I") | str_starts(sector_code,"3.J"),"Amount applied (t/yr)",activity_unit)) %>% 
    select(sector,sector_check,sector_code,sector_level,sector_description,activity_unit,activity,everything())
  
  
  ## recalculate 3C (rice) total
  blarg <- table_agriculture %>% 
    filter(sector_check %in% c("3.C.1. Irrigated","3.C.2. Rain-fed ","3.C.3. Deep water","3.C.4. Other (please specify)")) %>% 
    mutate(e_ch4=as.numeric(e_ch4))
  
  table_agriculture <- table_agriculture %>% 
    mutate(e_ch4=ifelse(sector_code=="3.C.",as.character(sum(blarg$e_ch4,na.rm=T)),e_ch4))
  
  
  ## recalculate 3D total
  blarg <- table_agriculture %>% 
    filter(sector_code %in% c("3.D.1.","3.D.2.")) %>% 
    mutate(e_n2o=as.numeric(e_n2o))
  
  table_agriculture <- table_agriculture %>% 
    mutate(e_n2o=ifelse(sector_code=="3.D.",as.character(sum(blarg$e_n2o,na.rm=T)),e_n2o))
  
  
  ## recalculate 3E total
  blarg <- table_agriculture %>% 
    filter(sector_code %in% c("3.E.1.","3.E.2.")) %>% 
    mutate(e_n2o=as.numeric(e_n2o),e_ch4=as.numeric(e_ch4))
  
  table_agriculture <- table_agriculture %>% 
    mutate(e_n2o=ifelse(sector_code=="3.E.",as.character(sum(blarg$e_n2o,na.rm=T)),e_n2o)) %>% 
    mutate(e_ch4=ifelse(sector_code=="3.E.",as.character(sum(blarg$e_ch4,na.rm=T)),e_ch4))
  
  
  ## recalculate 3F total
  blarg <- table_agriculture %>% 
    filter(sector_code %in% c("3.F.1.","3.F.2.","3.F.3.","3.F.4.","3.F.5.")) %>% 
    mutate(activity=as.numeric(activity),e_n2o=as.numeric(e_n2o),e_ch4=as.numeric(e_ch4))
  
  table_agriculture <- table_agriculture %>% 
    mutate(e_n2o=ifelse(sector_code=="3.F.",as.character(sum(blarg$e_n2o,na.rm=T)),e_n2o)) %>% 
    mutate(e_ch4=ifelse(sector_code=="3.F.",as.character(sum(blarg$e_ch4,na.rm=T)),e_ch4)) %>% 
    mutate(activity=ifelse(sector_code=="3.F.",as.character(sum(blarg$activity,na.rm=T)),activity))
  
  
  
  
  # merge manure management
  table_agriculture <- table_agriculture %>% 
    group_by(sector,sector_code) %>% 
    mutate(e_ch4=first(e_ch4),
           e_n2o=last(e_n2o)) %>% 
    select(-sector_check) %>% 
    distinct()
  
  
  # sum liming activities if empty
  table_agriculture <- table_agriculture %>%
    mutate(activity=ifelse(sector_code=="3.G." & is.na(activity),
                           as.character(sum(as.numeric(table_agriculture$activity[grepl("3.G.",table_agriculture$sector_code)]),na.rm=T)),
                           activity))
  
  
  table_agriculture <- table_agriculture %>%  
    filter(!is.na(sector_level))
  
  
  ## join everything
  table <- bind_rows(table_fuel_combustion,table_fugitive,table_ippu,table_agriculture) %>% 
    select(-sector_check)
  
  
  ## deal with NA, NO, IE, NE and convert to numeric
  table <- table %>% 
    mutate(across(c(activity,e_co2,e_ch4,e_n2o,cr_co2_fossil,cr_co2_bio,cr_ch4,cr_n2o),
                  ~ if_else(.x == "NO", "0", .x))) %>% 
    mutate(across(c(activity,e_co2,e_ch4,e_n2o,cr_co2_fossil,cr_co2_bio,cr_ch4,cr_n2o),
                  ~ if_else(str_detect(.x, "\\b(NA|NE|NO|IE|C)(,\\b(NA|NE|NO|IE|C))*\\b"), NA_character_, .x))) %>% 
    mutate(across(c(activity,e_co2,e_ch4,e_n2o,cr_co2_fossil,cr_co2_bio,cr_ch4,cr_n2o), as.numeric))
    
  
  ## join country and year
  table <- table %>% 
    mutate(iso=files_crts$iso[i]) %>% 
    mutate(country=files_crts$country[i]) %>% 
    mutate(year=files_crts$file_year[i])
  
  
  ## organise and join
  table <- table %>% 
    select(iso,country,year,everything()) 
  
  
  data_crts_activity <- bind_rows(data_crts_activity,table)
  
}


save(data_crts_activity,file="data/data_crts_activity_v2.RData")

```




```{r get_activity_data_energy_fuelcombustion}

i=50
data_crts_activity <- data.frame()


for (i in 1:length(files_crts$country)) {
  
  table_1 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s1"),
                       startRow = 7)
  
  table_2 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s2"),
                       startRow = 7)
  
  table_3 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s3"),
                       startRow = 7) %>% mutate(blarg=NA)
  
  table_4 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
                       sheet = paste0("Table1.A(a)s4"),
                       startRow = 7)
  
  
  names(table_1) <- c("sector","activity","X3","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2")
  names(table_2) <- c("sector","activity","X3","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2")
  names(table_3) <- c("sector","activity","X3","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2")
  names(table_4) <- c("sector","activity","X3","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2")
  
  
  table_1 <- table_1 %>% 
    select(-X3) %>% 
    mutate(activity_unit="Energy consumption (TJ)") %>% 
    select(sector,activity_unit,everything()) %>% 
    filter(!is.na(sector)) %>% 
    filter(!grepl("Note:",sector))
  
  table_2 <- table_2 %>% 
    select(-X3) %>% 
    mutate(activity_unit="Energy consumption (TJ)") %>% 
    select(sector,activity_unit,everything()) %>% 
    filter(!is.na(sector)) %>% 
    filter(!grepl("Note:",sector))
  
  table_3 <- table_3 %>% 
    select(-X3) %>% 
    mutate(activity_unit="Energy consumption (TJ)") %>% 
    select(sector,activity_unit,everything()) %>% 
    filter(!is.na(sector)) %>% 
    filter(!grepl("Note:",sector))
  
  table_4 <- table_4 %>% 
    select(-X3) %>% 
    mutate(activity_unit="Energy consumption (TJ)") %>% 
    select(sector,activity_unit,everything()) %>% 
    filter(!is.na(sector)) %>% 
    filter(!grepl("Note:",sector))
  
  
  ## remove footnotes
  table_4 <- table_4 %>% mutate(remove=ifelse(grepl("Information item",sector),"yes",NA))
  table_4$remove <- na.locf(table_4$remove,na.rm=FALSE)
  table_4 <- table_4 %>% 
    filter(is.na(remove)) %>% 
    select(-remove)
  
  
  ## join tables
  table <- bind_rows(table_1,table_2,table_3,table_4)
  
  
  ## clean
  table <- table %>% 
    filter(!grepl("Drop-down list:",sector))
    
  
  ## extract and propagate sector codes
  table <- table %>% 
    mutate(fuel = ifelse(str_detect(sector, "^[^0-9]"), sector, NA)) %>% 
    mutate(sector = ifelse(str_detect(sector, "^[^0-9]"), NA, sector)) %>% 
    mutate(sector_code=sub("^(\\S+)\\s.*", "\\1", sector))
  
  
  ## remove sector codes that don't start with a number and propagate
  table <- table %>% 
    mutate(sector_code = ifelse(grepl("^[0-9]",sector_code),sector_code,NA)) %>% 
    mutate(sector_code = na.locf(sector_code))
  
  
  ## add trailing dots to sector codes that don't have them
  table <- table %>% 
    mutate(sector_code = if_else(str_ends(sector_code, "\\.$"), sector_code, paste0(sector_code, ".")))
  
  
  ## remove sector codes from the descriptions and propagate
  table <- table %>% 
    mutate(sector = ifelse(grepl("^[0-9]",sector),sub("^\\S+\\s(.*)", "\\1", sector),sector)) %>% 
    mutate(sector = na.locf(sector))
  
  
  ## arrange and clean up fuels
  table <- table %>% 
    select(sector_code,sector,fuel,everything()) %>% 
    mutate(fuel=ifelse(is.na(fuel),"Total",fuel))
  
  
  # delete other fuels (please specify) rows, as they already have child rows
  table <- table %>% 
    filter(!grepl("please specify",fuel))
  
  
  ## remove spaces at the beginning of categories
  table$sector <- gsub("^\\s+", "", table$sector)
  
  
  ## deal with NA, NO, IE, NE and convert to numeric
  table <- table %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ if_else(.x == "NO", "0", .x))) %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "IE"))) %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "NA"))) %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "NE"))) %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "IE,NO"))) %>%  
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "IE,NA,NO"))) %>%  
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), ~ na_if(.x, "NA,NO"))) %>% 
    mutate(across(c(activity,ef_co2,ef_ch4,ef_n2o,e_co2,e_ch4,e_n2o,captured_co2), as.numeric))
  
  
  ## extract the emissions hierarchy (just the level associated with each sector)
  # table <- table %>%
  #   mutate(sector_level = map_int(sector_code, ~ sum(str_split(.x, "\\.")[[1]] != "")))
  
  
  ## remove subcategories of 1.A.2.g. (Manufacturing and industries other... too much detail)
  # table <- table %>% 
  #   filter(!(str_starts(sector_code, "1.A.2.g.") & sector_code != "1.A.2.g."))
  
  
  ## join country and year
  table <- table %>% 
    mutate(iso=files_crts$iso[i]) %>% 
    mutate(country=files_crts$country[i]) %>% 
    mutate(year=files_crts$file_year[i])
  
  
  ## organise and join
  table <- table %>% 
    select(iso,country,sector_code,sector_description=sector,fuel,year,everything()) 
  
  
  data_crts_activity <- bind_rows(data_crts_activity,table)
  
}


```

``` {r clean_energy_sectors}

data <- data_crts_activity

data <- data %>%
  select(-sector_description) %>% 
  left_join(.,cc_sectors,by="sector_code") %>% 
  filter(!is.na(sector_level)) %>% 
  select(country,iso,sector,sector_code,sector_level,sector_description,everything())


## remove fuel text within round brackets
data$fuel <- gsub("\\(.*?\\)", "", data$fuel)
data$fuel <- gsub("\\s+$", "", data$fuel)


## identify leaf nodes
data <- data %>%
  mutate(is_leaf = !sapply(sector_code, function(code) {
    any(str_detect(setdiff(sector_code, code), paste0("^", str_replace_all(code, "\\.", "\\\\."))))
  }))


## "Total" fuel estimates are not leaf nodes, unless they have no child fuels
data <- data %>% 
  group_by(sector_code,sector_level,sector_description) %>% 
  mutate(n=n()) %>% 
  mutate(is_leaf=ifelse(fuel=="Total" & n!=1,FALSE,is_leaf)) %>% 
  select(-n) %>% 
  ungroup()


## remove biomass CO2 emissions as its not in totals
data <- data %>% 
  mutate(e_co2=ifelse(fuel=="Biomass",0,e_co2))

```



``` {r clean_energy_fuelcombustion_data}
# 
# data <- data_crts_activity
# 
# ## remove trailing spaces in sector descriptions, text within round brackets
# data$sector_description <- gsub("\\(.*?\\)", "", data$sector_description)
# data$sector_description <- gsub("\\s+$", "", data$sector_description)
# data$fuel <- gsub("\\(.*?\\)", "", data$fuel)
# data$fuel <- gsub("\\s+$", "", data$fuel)
# 
# 
# ## identify leaf nodes
# sectors <- data %>% select(sector_code,sector_level,sector_description,fuel) %>% distinct()
# sectors <- sectors %>%
#   mutate(is_leaf = !sapply(sector_code, function(code) {
#     any(str_detect(setdiff(sector_code, code), paste0("^", str_replace_all(code, "\\.", "\\\\."))))
#   }))
# 
# 
# ## "Total" fuel estimates are not leaf nodes, unless they have no child fuels
# sectors <- sectors %>% 
#   group_by(sector_code,sector_level,sector_description) %>% 
#   mutate(n=n()) %>% 
#   mutate(is_leaf=ifelse(fuel=="Total" & n!=1,FALSE,is_leaf)) %>% 
#   select(-n) %>% 
#   ungroup()
# 
# 
# ## propagate sector_lv1
# sectors <- sectors %>% 
#   mutate(sector_lv1="Energy")
# 
# 
# ## propagate sector_lv2
# sectors <- sectors %>% 
#   mutate(match = substr(sector_code,1,3)) %>% 
#   left_join(.,sectors %>% 
#               filter(sector_level==2) %>%
#               mutate(match=substr(sector_code,1,3)) %>% 
#               select(match,sector_lv2=sector_description) %>% 
#               distinct(),
#             by = join_by(match)) %>% 
#   select(-match)
# 
# 
# ## propagate sector_lv3
# sectors <- sectors %>% 
#   mutate(match = substr(sector_code,1,5)) %>% 
#   left_join(.,sectors %>% 
#               filter(sector_level==3) %>%
#               mutate(match=substr(sector_code,1,5)) %>% 
#               select(match,sector_lv3=sector_description) %>% 
#               distinct(),
#             by = join_by(match)) %>% 
#   select(-match)
# 
# 
# ## propagate sector_lv4
# sectors <- sectors %>% 
#   mutate(match = substr(sector_code,1,8)) %>% 
#   left_join(.,sectors %>% 
#               filter(sector_level==4) %>%
#               mutate(match=substr(sector_code,1,8)) %>% 
#               select(match,sector_lv4=sector_description) %>% 
#               distinct(),
#             by = join_by(match)) %>% 
#   select(-match)
# 
# 
# ## clean up sectors (no double counting, all codes separate)
# sector_summary <- sectors
# sectors <- sectors %>% 
#   filter(is_leaf==TRUE)
# 
# 
# ## rejoin
# data <- left_join(data,sectors,by=join_by(sector_code,sector_level,sector_description,fuel))
# 
# 
# ## remove biomass CO2 emissions as its not in totals
# data <- data %>% 
#   mutate(e_co2=ifelse(fuel=="Biomass",0,e_co2))
# 


```


```{r check_totals}


#### check that different levels in the hierarchy add up


## calculate totals in non-leaf nodes
data_totals <- data %>% 
  filter(is.na(is_leaf)) %>% 
  group_by(iso,country,sector_code,sector_level,sector_description,fuel,year) %>% 
  summarise(activity_total=sum(activity,na.rm=T),
            e_co2_total=sum(e_co2,na.rm=T),
            e_ch4_total=sum(e_ch4,na.rm=T),
            e_n2o_total=sum(e_n2o,na.rm=T))


## check leaf nodes sum up
data_test <- data %>% 
  filter(!is.na(is_leaf)) %>% 
  group_by(iso,country,sector_code,sector_level,sector_description,year) %>% 
  summarise(activity=sum(activity,na.rm=T),
            e_co2=sum(e_co2,na.rm=T),
            e_ch4=sum(e_ch4,na.rm=T),
            e_n2o=sum(e_n2o,na.rm=T))


data_test <- left_join(data_test,data_totals) %>%
  mutate(check=ifelse(round(activity,6)!=round(activity_total,6),1,0)) %>%
  mutate(check=ifelse(round(e_co2,6)!=round(e_co2_total,6),check+1,check)) %>%
  mutate(check=ifelse(round(e_ch4,6)!=round(e_ch4_total,6),check+1,check)) %>%
  mutate(check=ifelse(round(e_n2o,6)!=round(e_n2o_total,6),check+1,check)) %>% 
  filter(check!=0)


## check hierarchy at lv4
data_totals <- data %>% 
  filter(fuel=="Total") %>% 
  filter(is.na(is_leaf)) %>% 
  group_by(iso,country,sector_code,sector_level,sector_description,year) %>% 
  summarise(activity_total=sum(activity,na.rm=T),
            e_co2_total=sum(e_co2,na.rm=T),
            e_ch4_total=sum(e_ch4,na.rm=T),
            e_n2o_total=sum(e_n2o,na.rm=T))


data_test <- data %>%
  filter(is_leaf==TRUE) %>% 
  mutate(sector_description=sector_lv4) %>% 
  group_by(iso,country,sector_description,year) %>% 
  summarise(activity=sum(activity,na.rm=T),
            e_co2=sum(e_co2,na.rm=T),
            e_ch4=sum(e_ch4,na.rm=T),
            e_n2o=sum(e_n2o,na.rm=T))


data_test <- left_join(data_test,data_totals) %>%
  mutate(check=ifelse(round(activity,6)!=round(activity_total,6),1,0)) %>%
  mutate(check=ifelse(round(e_co2,6)!=round(e_co2_total,6),check+1,check)) %>%
  mutate(check=ifelse(round(e_ch4,6)!=round(e_ch4_total,6),check+1,check)) %>%
  mutate(check=ifelse(round(e_n2o,6)!=round(e_n2o_total,6),check+1,check)) %>% 
  filter(check!=0)


```

```{r save}

data_crts_totals <- data %>% filter(is.na(sector_lv1))

## tidy up sector hierarchy
data <- data %>% filter(!is.na(sector_lv1))

data_crts_activity <- data
save(data_crts_activity,sector_summary,file="data/data_crts_activity.RData")


```



```{r get_activity_data_industry}
# 
# 
# for (i in 1:length(files_crts$country)) {
#   
#   table_1 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
#                        sheet = paste0("Table2(I).A-H"),
#                        startRow = 7)
#   
#   
#   names(table_1) <- c("category","activity_unit","activity","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2","captured_co2b","captured_ch4","captured_n2o")
#   
#   
#   table_1 <- table_1 %>% 
#     mutate(activity_unit=ifelse(!is.na(activity_unit),paste0(activity_unit," (kt)"),activity_unit)) %>% 
#     select(category,activity_unit,everything()) %>% 
#     filter(!is.na(category)) %>%
#     filter(category!="SINK CATEGORIES")
#   
#   
#   ## remove footnotes starting with "(1) ..."
#   table_1 <- table_1 %>% 
#     mutate(remove=NA) %>% 
#     mutate(remove=ifelse(grepl("^\\(1\\)",category),"yes",NA))
#   table_1$remove <- na.locf(table_1$remove,na.rm=FALSE)
#   table_1 <- table_1 %>% 
#     filter(is.na(remove)) %>% 
#     select(-remove)
#   
#   
#   ## extract category codes
#   table <- table_1 %>% 
#     mutate(category_code=sub("^(\\S+)\\s.*", "\\1", category)) %>% 
#     mutate(category=sub("^\\S+\\s(.*)", "\\1", category)) %>% 
#     mutate(category_code=ifelse(grepl("^[^0-9]",category_code),NA,category_code)) %>% 
#     mutate(temp=na.locf(category_code)) %>% 
#     mutate(category_code=ifelse(is.na(category_code),paste0(temp,"i"),category_code)) %>% 
#     select(-temp)
#   
#   
#   ## fix a typo where some descriptions are joined to the category_code
#   table$category_code <- gsub("Other","",table$category_code)
#   
#   
#   ## remove spaces at the beginning of categories
#   table$category <- gsub("^\\s+", "", table$category)
#   
#   
#   ## replace "NO"s with zeros (also what does IE mean?)
#   
#   
#   ## extract the emissions hierarchy (just the level associated with each category)
#   table <- table %>%
#     mutate(category_level = map_int(category_code, ~ sum(str_split(.x, "\\.")[[1]] != "")))
#   
#   
#   ## join country and year
#   table <- table %>% 
#     mutate(iso=files_crts$country[i]) %>% 
#     mutate(year=files_crts$file_year[i])
#   
#   
#   ## organise
#   table <- table %>% 
#     select(iso,category_code,category_level,category_description=category,year,everything()) 
#   
#   
#   data_crts_activity <- bind_rows(data_crts_activity,table)
#   
# }
# 

```

```{r get_activity_data_agriculture}
# 
# for (i in 1:length(files_crts$country)) {
#   
#   table_1 <- read.xlsx(xlsxFile = paste0("sources/CRTs/",files_crts$dir[i],"/",files_crts$files[i]),
#                        sheet = paste0("Table2(I).A-H"),
#                        startRow = 7)
#   
#   
#   names(table_1) <- c("category","activity_unit","activity","ef_co2","ef_ch4","ef_n2o","e_co2","e_ch4","e_n2o","captured_co2","captured_co2b","captured_ch4","captured_n2o")
#   
#   
#   table_1 <- table_1 %>% 
#     mutate(activity_unit=ifelse(!is.na(activity_unit),paste0(activity_unit," (kt)"),activity_unit)) %>% 
#     select(category,activity_unit,everything()) %>% 
#     filter(!is.na(category)) %>%
#     filter(category!="SINK CATEGORIES")
#   
#   
#   ## remove footnotes starting with "(1) ..."
#   table_1 <- table_1 %>% 
#     mutate(remove=NA) %>% 
#     mutate(remove=ifelse(grepl("^\\(1\\)",category),"yes",NA))
#   table_1$remove <- na.locf(table_1$remove,na.rm=FALSE)
#   table_1 <- table_1 %>% 
#     filter(is.na(remove)) %>% 
#     select(-remove)
#   
#   
#   ## extract category codes
#   table <- table_1 %>% 
#     mutate(category_code=sub("^(\\S+)\\s.*", "\\1", category)) %>% 
#     mutate(category=sub("^\\S+\\s(.*)", "\\1", category)) %>% 
#     mutate(category_code=ifelse(grepl("^[^0-9]",category_code),NA,category_code)) %>% 
#     mutate(temp=na.locf(category_code)) %>% 
#     mutate(category_code=ifelse(is.na(category_code),paste0(temp,"i"),category_code)) %>% 
#     select(-temp)
#   
#   
#   ## fix a typo where some descriptions are joined to the category_code
#   table$category_code <- gsub("Other","",table$category_code)
#   
#   
#   ## remove spaces at the beginning of categories
#   table$category <- gsub("^\\s+", "", table$category)
#   
#   
#   ## replace "NO"s with zeros (also what does IE mean?)
#   
#   
#   ## extract the emissions hierarchy (just the level associated with each category)
#   table <- table %>%
#     mutate(category_level = map_int(category_code, ~ sum(str_split(.x, "\\.")[[1]] != "")))
#   
#   
#   ## join country and year
#   table <- table %>% 
#     mutate(iso=files_crts$country[i]) %>% 
#     mutate(year=files_crts$file_year[i])
#   
#   
#   ## organise
#   table <- table %>% 
#     select(iso,category_code,category_level,category_description=category,year,everything()) 
#   
#   
#   data_crts_activity <- bind_rows(data_crts_activity,table)
#   
# }

```
